version: "3"

services:
  shopmanager:
    build: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    entrypoint: ["python", "app_dev.py"]
    environment:
      - DEVICE=${DEVICE}
      - BATCH_SIZE=${BATCH_SIZE}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_PUBLISH_TOPIC=${KAFKA_PUBLISH_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - API_PORT=${API_PORT}
      - NUM_RETRY=${NUM_RETRY}
      - MAX_RAM_CACHE_SIZE=${MAX_RAM_CACHE_SIZE}
      - MAX_PROCESS_WORKERS=${MAX_PROCESS_WORKERS}
      - CACHE_TYPE=${CACHE_TYPE}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_ENDPOINT=${CACHE_ENDPOINT}
      - CACHE_ENDPOINT_TYPE=${CACHE_ENDPOINT_TYPE}
    ports:
      - "20236:8080"
    networks:
      - ChatBot

networks:
  ChatBot:
    external: true