from TMTChatbot.Common.config.config import Config as BaseConfig


class Config(BaseConfig):

    def __init__(self,
                 mongo_host: str = None,
                 mongo_port: int = None,
                 mongo_username: str = None,
                 mongo_password: str = None,
                 mongo_database: str = None,
                 kafka_consume_topic: str = None,
                 kafka_publish_topic: str = None,
                 kafka_bootstrap_servers: str = None,
                 kafka_auto_offset_reset: str = None,
                 kafka_group_id: str = None,
                 api_port: int = None,
                 num_try: int = None,
                 external_failed_timeout: int = None,
                 max_ram_cache_size: int = None,
                 max_process_workers: int = None,
                 logging_folder: str = None,
                 log_name: str = None,
                 cache_host: str = None,
                 cache_port: str = None,
                 cache_endpoint: str = None,
                 cache_type: str = None,
                 cache_endpoint_type: str = None,
                 graph_qa_url: str = None,
                 intent_url: str = None,
                 ner_url: str = None,
                 doc_qa_url: str = None,
                 node_search_url: str = None,
                 address_url: str = None,
                 multiple_choice_url: str = None,
                 bill_image_service_url: str = None,
                 node_image_search_url: str = None,
                 weather_url: str = None,
                 size_prediction_url: str = None,
                 response_delimiter: str = "*",
                 bill_generation_url: str = None):
        super(Config, self).__init__(mongo_host=mongo_host, mongo_port=mongo_port, mongo_username=mongo_username,
                                     mongo_password=mongo_password, mongo_database=mongo_database,
                                     kafka_consume_topic=kafka_consume_topic, kafka_publish_topic=kafka_publish_topic,
                                     kafka_bootstrap_servers=kafka_bootstrap_servers,
                                     kafka_auto_offset_reset=kafka_auto_offset_reset, kafka_group_id=kafka_group_id,
                                     api_port=api_port, num_try=num_try,
                                     external_failed_timeout=external_failed_timeout,
                                     max_ram_cache_size=max_ram_cache_size, max_process_workers=max_process_workers,
                                     logging_folder=logging_folder, log_name=log_name, cache_host=cache_host,
                                     cache_port=cache_port, cache_endpoint=cache_endpoint, cache_type=cache_type,
                                     cache_endpoint_type=cache_endpoint_type, graph_qa_url=graph_qa_url,
                                     intent_url=intent_url, ner_url=ner_url, node_search_url=node_search_url,
                                     doc_qa_url=doc_qa_url, address_url=address_url,
                                     response_delimiter=response_delimiter, multiple_choice_url=multiple_choice_url,
                                     bill_image_service_url=bill_image_service_url,
                                     node_image_search_url=node_image_search_url,
                                     weather_url=weather_url, bill_generation_url=bill_generation_url,
                                     size_prediction_url=size_prediction_url)
